'use strict';
// Ссылки на видео с техникой (из файла тренировок)
const VIDEO = {
 "Вертикальная тяга блока параллельным хватом": "https://www.youtube.com/shorts/JtiAnzniARA",
 "Вертикальная тяга блока узким хватом": "https://www.youtube.com/shorts/qxAjVptyK-4",
 "Вертикальная тяга блока широким хватом": "https://www.youtube.com/shorts/WVtkxdAoDqs",
 "Выпады с гантелями / штангой": "https://www.youtube.com/shorts/ukabBzBGVO0",
 "Горизонтальная тяга блока по 1-й руке": "https://www.youtube.com/shorts/ANLNqnvtn5I",
 "Горизонтальная тяга блока с акцентом на ширину": "https://www.youtube.com/shorts/1iU65ToLyB0",
 "Жим в Смите в наклоне": "https://www.youtube.com/shorts/UA2uuAElBcE",
 "Жим в Хаммере на верх груди": "https://www.youtube.com/shorts/_pbCAfy8vDM",
 "Жим в Хаммере на низ груди": "https://www.youtube.com/shorts/ppVWVWaijPw",
 "Жим гантелей в наклоне": "https://www.youtube.com/shorts/CAXdA9iEXco",
 "Жим гантелей лежа": "https://www.youtube.com/shorts/RF_Z4an3FTM",
 "Жим гантелей сидя": "https://www.youtube.com/shorts/_Hng2oWkj3w",
 "Жим ногами": "https://www.youtube.com/shorts/pdmAAyqaJos",
 "Мертвая тяга": "https://www.youtube.com/shorts/lmfltWWJDpM",
 "Молитва в блоке": "https://www.youtube.com/shorts/TftUxOBcE1o",
 "Молотки с канатом": "https://www.youtube.com/shorts/ozHyAhP8ZFs",
 "Отведение в кроссовере по 1-й руке": "https://www.youtube.com/shorts/9fF7OUuzjMM",
 "Отведение гантелей в стороны стоя": "https://www.youtube.com/shorts/sae4gLqTFEs",
 "Отведение гантелей с упором в скамью": "https://www.youtube.com/shorts/nMz2V_3WCZs",
 "Отведение рук в кроссовере лежа": "https://www.youtube.com/shorts/HgkIGr6nMVA",
 "Подъем гантелей на бицепс сидя на наклонной скамье": "https://www.youtube.com/shorts/bmMpgxzJhWE",
 "Подъем штанги на бицепс": "https://www.youtube.com/shorts/_8l82_jZl3Y",
 "Подъемы на носки в тренажере сидя": "https://www.youtube.com/shorts/2DAHyNcTtGA",
 "Подъемы на носки в тренажере стоя / в Смите": "https://www.youtube.com/shorts/ZBWBiCu_xJE",
 "Подъемы ног в висе": "https://www.youtube.com/shorts/smyfMQh-Rms",
 "Приседания в Гакке": "https://www.youtube.com/shorts/bmXRE774bvY",
 "Приседания в Смите": "https://www.youtube.com/shorts/4SAL2nh4e2g",
 "Протяжка с нижнего блока": "https://www.youtube.com/shorts/7TVpuq6Stkg",
 "Пулловер в блоке с упором спиной": "https://www.youtube.com/watch?v=DiO10H1UTZU",
 "Разведение гантелей с упором в скамью (задняя дельта)": "https://www.youtube.com/shorts/dOrZ_MHKUBo",
 "Разведение на заднюю дельту в Peck-Deck": "https://www.youtube.com/shorts/SpeJD8WSRP0",
 "Разгибания в блоке по 1-й руке": "https://www.youtube.com/shorts/WdGzJ-lZVMg",
 "Разгибания в блоке с прямой рукоятью": "https://www.youtube.com/shorts/ZJDVfLJms2s",
 "Разгибания из-за головы в блоке": "https://www.youtube.com/shorts/w3tzPoxhKQE",
 "Разгибания из-за головы в блоке по 1-й руке": "https://www.youtube.com/shorts/HObNZxHcfXM",
 "Разгибания ног в тренажере": "https://www.youtube.com/shorts/U8ZffkVs9dw",
 "Разгибания с гантелью из-за головы по 1-й руке": "https://www.youtube.com/shorts/xl6S_IhFCb4",
 "Рычажная горизонтальная тяга по 1-й руке": "https://www.youtube.com/shorts/Oj_F4Cg5UVo",
 "Сведение в Peck-Deck на низ груди": "https://www.youtube.com/shorts/Jdj_asaMtvM",
 "Сведение в кроссовере лежа на наклонной скамье": "https://www.youtube.com/shorts/xODrGtfCD-M",
 "Сведение в кроссовере стоя": "https://www.youtube.com/shorts/5bBYLCo_lKU",
 "Сгибания ног на бицепс бедра в тренажере стоя по 1-й ноге": "https://www.youtube.com/shorts/07k0M54QF1c",
 "Сгибания рук в тренажере Скотта": "https://www.youtube.com/shorts/J_VVlkVzH38",
 "Сгибания рук с нижнего блока": "https://www.youtube.com/shorts/-k_vFGb4Lbw",
 "Тяга гантелей с упором в скамью": "https://www.youtube.com/shorts/J_qqm8yZFBM",
 "Тяга нижнего блока с упором в скамью": "https://www.youtube.com/shorts/r0d0RCR5hJ4"
};
const WARMUP = {"upper": "https://www.youtube.com/shorts/NgP5ePNPF8I", "lower": "https://www.youtube.com/shorts/syQ_R_G6sX8"};
